services:
  # --- BASE DE DATOS ---
  db:
    image: postgres:15
    container_name: prieto-eats-db
    restart: always
    ports:
      - 5000:80
    environment:
      POSTGRES_DB: prieto_eats
      POSTGRES_USER: m_carmen
      POSTGRES_PASSWORD: prieto_eats_mcarmen
    volumes:
      - db_data:/var/lib/postgresql/data


  # --- APLICACIÓN ---
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prieto-eats
    restart: always
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=prietoeats-mcarmen.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=80
    depends_on:
      - db

volumes:
  db_data:
